### ISSUE TITLE
Florence 2 models do not work.

### ISSUE THREAD

**Issue by Dinsmoor** [reasv/panoptikon#6]
When checking the "all" button and trying to run these models, none work.

![image](https://github.com/user-attachments/assets/26ba815b-1538-4a31-a1e2-b2d5bab7bd20)

With those selected, here is the output from launch:

```python
2024-12-16 00:11:28,973 [INFO][panoptikon.api.routers.jobs.manager] - Enqueued job 15: data_extraction
2024-12-16 00:11:28,974 [INFO][panoptikon.api.routers.jobs.manager] - Enqueued job 16: data_extraction
2024-12-16 00:11:28,974 [INFO][panoptikon.api.routers.jobs.manager] - Enqueued job 17: data_extraction
2024-12-16 00:11:28,974 [INFO][panoptikon.api.routers.jobs.manager] - Enqueued job 18: data_extraction
2024-12-16 00:11:28,975 [INFO][panoptikon.api.routers.jobs.manager] - Enqueued job 19: data_extraction
2024-12-16 00:11:28,975 [INFO][panoptikon.api.routers.jobs.manager] - Enqueued job 20: data_extraction
2024-12-16 00:11:28,975 [INFO][panoptikon.api.routers.jobs.manager] - Enqueued job 21: data_extraction
2024-12-16 00:11:28,975 [INFO][panoptikon.api.routers.jobs.manager] - Enqueued job 22: data_extraction
2024-12-16 00:11:29,628 [INFO][panoptikon.api.routers.jobs.manager] - Dequeued job 15: data_extraction
2024-12-16 00:11:29,628 [INFO][panoptikon.api.routers.jobs.manager] - Starting job 15 in process None
2024-12-16 00:11:29,660 [INFO][panoptikon.data_extractors.dynamic_job] - No score threshold set
2024-12-16 00:11:31,276 [ERROR][inferio.process_model] - florence2 - Error during load: list.remove(x): x not in list
2024-12-16 00:11:31,276 [ERROR][inferio.process_model] - florence2 - Detected subprocess crash.
2024-12-16 00:11:31,276 [ERROR][inferio.process_model] - florence2 - Error loading model: list.remove(x): x not in list
Traceback (most recent call last):
  File "/mnt/storage/tmp/panoptikon/src/inferio/process_model.py", line 273, in _model_process
    model_instance.load()
  File "/mnt/storage/tmp/panoptikon/src/inferio/impl/florence2.py", line 70, in load
    AutoModelForCausalLM.from_pretrained(
  File "/home/tyler/.cache/pypoetry/virtualenvs/panoptikon-Vs-sSM2f-py3.12/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tyler/.cache/pypoetry/virtualenvs/panoptikon-Vs-sSM2f-py3.12/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 541, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tyler/.cache/pypoetry/virtualenvs/panoptikon-Vs-sSM2f-py3.12/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 366, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tyler/.cache/pypoetry/virtualenvs/panoptikon-Vs-sSM2f-py3.12/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 182, in check_imports
    imports = get_imports(filename)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/storage/tmp/panoptikon/src/inferio/impl/florence2.py", line 25, in fixed_get_imports
    imports.remove("flash_attn")
ValueError: list.remove(x): x not in list
2024-12-16 00:11:34,369 [ERROR][inferio.process_model] - florence2 - Exception during load: list.remove(x): x not in list
Traceback (most recent call last):

....... more of the same

```

Implementing a check in `src/inferio/impl/florence2.py` seems to have fixed it:
![image](https://github.com/user-attachments/assets/9cae9145-710c-449a-a6d6-20e1631259b4)

My images are now properly captioned and searchable.

**Comment by reasv** [comment]
Yes, the code is basically a workaround for some older versions of the library we're using unnecessarily requiring flash attention. It seems this requirement is gone from newer versions, so the check becomes necessary, though it'd probably even be fine to remove the function entirely. I'm going to just add the check for now.
